In [1]:
import time
import torch

print(torch.__version__)

2.4.0+cu121


In [8]:
x = [1, 2, 3, 4, 5]
x = torch.as_tensor(x)
print(x)
print(f"size = {x.size()}")
print(f"shape = {x.shape}")
print(f"dtype = {x.dtype}")
print(f"dimension = {x.dim()}")
print(f"device = {x.device}")

tensor([1, 2, 3, 4, 5])
size = torch.Size([5])
shape = torch.Size([5])
dtype = torch.int64
dimension = 1
device = cpu


In [9]:
x = torch.zeros(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [10]:
x = torch.ones(3, 4)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [11]:
x = torch.full((3, 4), fill_value=2)
print(x)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])


In [12]:
x = torch.randn(3, 4)
print(x)

tensor([[ 0.4354, -0.6730, -0.3934,  1.0608],
        [ 2.3621,  0.7313,  0.6525, -0.1140],
        [-0.1390, -0.1019, -1.6127, -0.6168]])


In [13]:
x = torch.randn(3, 4)
y = torch.zeros_like(x)
print(y)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [14]:
x = torch.randn(3, 4)
y = torch.ones_like(x)
print(y)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [15]:
x = torch.randn(3, 4)
y = torch.full_like(x, 5)
print(y)

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])


In [16]:
x = torch.zeros(3, 4, dtype=torch.bool)
y = x.new_tensor([1, 2, 3, 4])
print(y)

tensor([True, True, True, True])


In [17]:
x = torch.ones(5, 1)
y = torch.ones(1, 5)
z = x + y
print(z, z.shape)

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]]) torch.Size([5, 5])


In [18]:
x = torch.ones(1, 1, 1, 1, 1)
y = torch.ones(2, 1, 3, 1, 2)
z = x + y
print(z, z.shape)

tensor([[[[[2., 2.]],

          [[2., 2.]],

          [[2., 2.]]]],



        [[[[2., 2.]],

          [[2., 2.]],

          [[2., 2.]]]]]) torch.Size([2, 1, 3, 1, 2])


In [19]:
x = torch.ones(3, 4, 5)
print(x.mean())
print(x.mean(-1))

tensor(1.)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [20]:
x = torch.ones(3, 4, 5)
print(x.sum(dim=0))
print(x.sum(dim=(1, 2)))

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])
tensor([20., 20., 20.])


In [21]:
x = torch.ones(3, 4, 5)
y = x.sum(dim=(1, 2))
z = x.sum(dim=(1, 2), keepdim=True)
print(y, y.shape)
print(z, z.shape)

tensor([20., 20., 20.]) torch.Size([3])
tensor([[[20.]],

        [[20.]],

        [[20.]]]) torch.Size([3, 1, 1])


In [22]:
x = torch.randn(5, 5)
print(x.to(torch.long))

tensor([[-1,  0,  0,  0, -2],
        [ 0,  0,  1,  0,  0],
        [ 0,  0, -1,  1, -1],
        [ 1,  0,  0,  1,  1],
        [ 0,  0,  0,  0,  0]])


In [23]:
x = torch.randn(2, 3, 2)
y = x.view(6, 2)
z = x.view(-1, 2)
print(y, y.shape)
print(z, z.shape)

tensor([[-0.7375,  1.4060],
        [ 0.3494,  0.3088],
        [-0.7860, -1.1487],
        [-1.2708,  1.4033],
        [-0.3149, -1.0346],
        [ 1.6459,  0.1498]]) torch.Size([6, 2])
tensor([[-0.7375,  1.4060],
        [ 0.3494,  0.3088],
        [-0.7860, -1.1487],
        [-1.2708,  1.4033],
        [-0.3149, -1.0346],
        [ 1.6459,  0.1498]]) torch.Size([6, 2])


In [24]:
x = torch.randn(2, 3, 2)
y = x.permute(1, 2, 0)
print(y, y.shape)

tensor([[[-0.9200, -0.5458],
         [ 0.2720,  1.1355]],

        [[-1.0244, -0.1501],
         [ 1.2076,  0.3366]],

        [[-0.7689, -0.9289],
         [ 0.9748, -1.8684]]]) torch.Size([3, 2, 2])


In [25]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.cat([x, y], dim=0)
print(z, z.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) torch.Size([4, 3])


In [26]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
z = torch.stack([x, y], dim=1)
print(z, z.shape)

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]) torch.Size([2, 2, 3])


In [27]:
def add_two_lists(x, y):
    z = []
    for i, j in zip(x, y):
        z.append(i + j)
    return z


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

0.0482 sec.


In [28]:
def add_two_lists(x, y):
    return x + y


x = torch.ones(5000)
y = torch.ones(5000)
t1 = time.time()
z = add_two_lists(x, y)
print(f"{time.time() - t1:.4f} sec.")

0.0002 sec.


In [29]:
x = torch.randn(3, 3)
y = torch.zeros(5, 2, dtype=torch.long)
print(x.to(torch.float32))
print(x.to(torch.bool))
print(x.to(y))

tensor([[ 0.7302,  1.0639, -0.6764],
        [ 1.9761,  0.9864, -0.2111],
        [ 0.9022,  0.3866,  1.0079]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])
tensor([[0, 1, 0],
        [1, 0, 0],
        [0, 0, 1]])


In [30]:
x = torch.arange(8)
print(x)
y = torch.arange(2, 8)
print(y)
z = torch.arange(3, 10, step=2)
print(z)

tensor([0, 1, 2, 3, 4, 5, 6, 7])
tensor([2, 3, 4, 5, 6, 7])
tensor([3, 5, 7, 9])
